apiVersion: v1
items:
- apiVersion: storage.k8s.io/v1
  kind: CSIDriver
  metadata:
    creationTimestamp: "2024-03-12T17:39:10Z"
    name: fss.csi.oraclecloud.com
    resourceVersion: "444"
    uid: 458f9811-4d53-4c2e-adfd-3e0a877b6423
  spec:
    attachRequired: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    podInfoOnMount: false
    requiresRepublish: false
    seLinuxMount: false
    storageCapacity: false
    volumeLifecycleModes:
    - Persistent
- apiVersion: storage.k8s.io/v1
  kind: CSIDriver
  metadata:
    annotations:
      meta.helm.sh/release-name: oci-provider
      meta.helm.sh/release-namespace: oci-provider
    creationTimestamp: "2024-03-24T18:03:00Z"
    labels:
      app: secrets-store-csi-driver
      app.kubernetes.io/instance: oci-provider
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: secrets-store-csi-driver
      app.kubernetes.io/version: 1.3.3
      helm.sh/chart: secrets-store-csi-driver-1.3.3
    name: secrets-store.csi.k8s.io
    resourceVersion: "4454246"
    uid: 1c9b13d4-2bc3-4f2a-95a4-09a10a8413d1
  spec:
    attachRequired: false
    fsGroupPolicy: ReadWriteOnceWithFSType
    podInfoOnMount: true
    requiresRepublish: false
    seLinuxMount: false
    storageCapacity: false
    tokenRequests:
    - audience: ""
    volumeLifecycleModes:
    - Ephemeral
kind: List
metadata:
  resourceVersion: ""
