apiVersion: v1
entries:
  oci-secrets-store-csi-driver-provider:
  - apiVersion: v2
    appVersion: 0.9.2
    created: "2023-04-20T10:28:07.029444855Z"
    dependencies:
    - condition: secrets-store-csi-driver.install
      name: secrets-store-csi-driver
      repository: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
      version: 1.2.0
    description: OCI Vault provider for the Secrets Store CSI driver.
    digest: 66a5d4eb581a95c64f4d3639452cfa7d9f08ad9d83e7a8898b173070bb7d9ae3
    keywords:
    - oci
    - secrets-store-csi-driver-provider
    kubeVersion: '>=1.19.0-0'
    maintainers:
    - name: OKE Foundations team
    name: oci-secrets-store-csi-driver-provider
    type: application
    urls:
    - https://rajashekhargundeti.github.io/oci-secrets-store-csi-driver-provider/charts/oci-secrets-store-csi-driver-provider-0.2.5.tgz
    version: 0.2.5
generated: "2023-04-20T10:28:07.027194545Z"
