name: Release Charts

# on:
#   push:
#     # Build and publish artifacts for a release
#     tags:
#       - "t*.*.*"

on:
  push:
    branches:
      - helm-release-action

jobs:
  release-chart:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    # permissions:
    #   contents: write
    runs-on: ubuntu-latest
    env:
      IMAGE_PATH: ghcr.io/rajashekhargundeti/oci-secrets-store-csi-driver-provider:26fa05efa2d70964fbf01de8fef2f54441527503
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # - name: Configure Git
      #   run: |
      #     git config user.name "$GITHUB_ACTOR"
      #     git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      # - name: Install Helm
      #   uses: azure/setup-helm@v3

      - name: split image path into repo and tag
        id: split-image-path
        run: |
          echo PROVIDER_IMAGE_REPO=`echo ${{ env.IMAGE_PATH }} | sed -e "s/:.*$//"` >> $GITHUB_ENV
          echo PROVIDER_IMAGE_TAG=`echo ${{ env.IMAGE_PATH }} | sed -e "s/.*://"` >> $GITHUB_ENV

      - name: print
        run: echo ${{ env.PROVIDER_IMAGE_REPO }} ${{ env.PROVIDER_IMAGE_TAG }}    